const { smd } = require("../lib");

// Array of questions
const questions = [
  "1. Which phone are u using?",
  "2. Do you have a crush?",
  "3. Do u like sex chatting?",
  "4. How did u feel about me?",
  "5. We are left in a room and I'm horny, I asked you to help me out. What would you do?",
  "6. Do you go for night parties?",
  "7. Have you ever smoked before?",
  "8. How many girls/guys have u dated?",
  "9. Do u masturbate?",
  "10. Tell me a story?",
  "11. What are u wearing now?",
  "12. Ever had a near death experience?",
  "13. If you had a chance would u date me?",
  "14. Big or small ass?",
  "15. What did u hate about me?",
  "16. What name would you give your pussy/Dick?",
  "17. Will u be mine if u given opportunity?",
  "18. What do you look out in your partner before dating him/her?",
  "19. Do u watch porn?",
  "20. If you had 3 wishes, what would they be?",
  "21. Best thing that ever happen to u?",
  "22. Light skinned or dark?",
  "23. Did u wear tight?",
  "24. Last time you had sex?",
  "25. Have you ever been touched by your fellow girl/guy?",
  "26. Do you enjoy porn?",
  "27. Do you like dirty talks?",
  "28. Something you would change about yourself?",
  "29. Any scars?",
  "30. Worst mistake?",
  "31. Can you stay in a room where two people are having sex?",
  "32. Someone u would die for?",
  "33. Watch the movie or read the book?",
  "34. Did u wear waist beads?",
  "35. Best body part?",
  "36. Worst thing that ever happen to u?",
  "37. Tell me everything you are wearing now?",
  "38. Something u are proud of?",
  "39. What's ur dream?",
  "40. Ever been abused?",
  "41. Can we fuck?",
  "42. Use my pic as ur dp for one week",
  "43. Will you let me fuck you?",
  "44. What lead to ur breakup in ur last relationship?",
  "45. When last did u feel like having sex?",
  "46. Are u single or taken?",
  "47. What type and colour of pant/boxer are you wearing now?",
  "48. Ever slept out?",
  "49. Can u marry someone that behaves like u?",
  "50. Ever snap nude pic?",
  "51. Last kiss?",
  "52. Girlfriend/Boyfriend name?",
  "53. What's the color of ur pantie & bra are u wearing now?",
  "54. How many are u in ur family?",
  "55. Ever cheated on ur bae/boo b4?",
  "56. Weight?",
  "57. First kiss?",
  "58. Player or loyal?",
  "59. What did u wish to do if I there?",
  "60. Who do you hate?",
  "61. Longest relationship?",
  "62. What will u do if I offend u?",
  "63. What do you love in me?",
  "64. Mention three sex positions u know?",
  "65. What's your fear in life?",
  "66. Favorite cloth?",
  "67. Did u wear bra now?",
  "68. What get u wet?",
  "69. Ever had sex?",
  "70. Girl/Boy Best friend?",
  "71. Are you naughty?",
  "72. Do u love fingering or sucking?",
  "73. Favorite body part of your opposite gender?",
  "74. Big pussy/dick or normal?",
  "75. What can I do to make u feel horny?",
  "76. Take a pic now and send to me?",
  "77. Which part of ur body did u play with whenever u are feeling bored?",
  "78. Send me your two sexiest pics.",
  "79. Which area did u live?",
  "80. Let me see your panties and bra/boxer while ur putting dem on.",
  "81. Your class or level?",
  "82. Age?",
  "83. What will be ur reaction if u see me?",
  "84. Last time u cried and what caused it?",
  "85. Your kind of man/woman?",
  "86. What's your mood right now?",
  "87. Tell me things u want us to do together.",
  "88. Best hobby?",
  "89. Can u let me finger/suck u?",
  "90. What turns you on before sex?",
  "91. Can u cook?",
  "92. If u see me naked, what will u do?",
  "93. Any tattoos?",
  "94. Hairy/shaved pussy/dick?",
  "95. What do you want from me?",
  "96. Best food?",
  "97. How much do u enjoy sex?",
  "98. Big breast or normal?",
  "99. Did u wish u could start over?",
  "100. Ever exchange nudes?",
  "101. What's ur talent?",
  "102. What will u do if I mistakenly touch ur breast?",
  "103. Worst mistake?",
  "104. Condom or raw?",
  "105. Full name?",
  "106. Has someone ever seen ur boobs?",
  "107. What's ur pant/boxer size?",
  "108. Will you let me kiss you?",
  "109. Will you let me touch you?",
  "110. Give me a sweet name.",
  "111. What will u do if I mistakenly kiss u?",
  "112. How long can u last on bed with ur partner?",
  "113. Can u cook?",
  "114. How do u feel when u watch porn?",
  "115. Something u can't do without?",
  "116. Can u dance?",
  "117. Ever kissed a friend?",
  "118. In what way have you cheated on your boo?",
  "119. Who's ur crush?",
  "120. Bra size?",
  "121. Best color?",
  "122. Can we be friends with benefits?",
  "123. Ever tasted sperm?",
  "124. Can u do a lap dance?",
  "125. Someone you can tell anything to?",
  "126. If you had 3 wishes, what would they be?",
  "127. Who can you die for?",
  "128. Ever smoked?",
  "129. Ever fingered urself?",
  "130. What's the naughtiest thing you've ever done?",
  "131. Ever slept naked?",
  "132. What will u do if I mistakenly kiss u?",
  "133. Can u twerk?",
  "134. Ever kissed someone of the same sex?",
  "135. Does naughty talk get u aroused?",
  "136. How long do u want sex to be?",
  "137. One of ur deepest secrets?",
  "138. Name of ur boo/bae?",
  "139. What's ur best subject?",
  "140. Describe me in one word?",
  "141. Which would u give me: a kiss, a lap dance, or sex?",
  "142. Favorite sex position?",
  "143. Who made u smile today?",
  "144. When last did u read ur Bible or Islamic book?",
  "145. Best part u love in a girl's body?",
  "146. Best part u love in a guy's body?",
  "147. Ever had the urge to have sex with me?",
  "148. When last did u pray?",
  "149. Do u have a serious lover or relationship?",
  "150. Do u love me?",
  "151. Send nudes.",
  "152. Can u send me a card?",
  "153. If you got pregnant or got someone pregnant, are you keeping the baby?",
  "154. What's your wildest fantasy?",
  "155. If you could have dinner with anyone, who would it be and why?",
  "156. What's the most daring thing you've ever done?",
  "157. If we were on a deserted island, what would you do to survive?",
  "158. What's the weirdest thing you've ever done in public?",
  "159. What's one secret you've never told anyone?",
  "160. If you could go back in time, what would you change about your love life?",
  "161. What's the most romantic thing you've ever done for someone?",
  "162. What's the most awkward date you've been on?",
  "163. Describe your ideal romantic evening.",
  "164. Have you ever sent a risky text to the wrong person?",
  "165. What's the best pickup line you've ever heard or used?",
  "166. What would you do if someone you liked kissed you out of the blue?",
  "167. What's the most unexpected place you've had a romantic moment?",
  "168. Have you ever fallen for someone you couldn't have?",
  "169. What's the most attractive quality in a person for you?",
  "170. If you could be invisible for a day, what would you do?",
  "171. Have you ever had a crush on a friend's partner?",
  "172. If I dared you to kiss me, would you?",
  "173. What's the longest you've gone without showering?",
  "174. What's the strangest thing you've found attractive in someone?",
"175. Have you ever had a crush on a teacher?",
  "176. What's the craziest thing you'd do for love?",
  "177. What's the most embarrassing thing that's happened to you during a romantic moment?",
  "178. If you could describe your love life in a song, what song would it be?",
  "179. What's the best compliment you've ever received?",
  "180. What's your biggest turn-off?",
  "181. Would you ever go skinny dipping?",
  "182. What's the most you've ever lied to get someone's attention?",
  "183. What's your guilty pleasure TV show or movie?",
  "184. Have you ever been caught doing something you shouldn't have?",
  "185. What's the strangest thing you've googled late at night?",
  "186. If you could only keep one secret forever, what would it be?",
  "187. Would you rather never find true love or never be intimate again?",
  "188. What's the most mischievous thing you've done at work or school?",
  "189. What's the most adventurous thing you've done on a date?",
  "190. Have you ever broken someone's heart?",
  "191. What would you do if your ex wanted to get back together?",
  "192. What's the most ridiculous thing you've ever done to impress someone?",
  "193. What would you do if you woke up next to your crush?",
  "194. If you could relive one romantic moment, which would it be?",
  "195. What's the most trouble you've gotten into at a party?",
  "196. What's your go-to move when flirting?",
  "197. If you had to choose between true love or $1 million, which would you pick?",
  "198. What's the sexiest outfit you own?",
  "199. Have you ever had a forbidden romance?",
  "200. If we played truth or dare, what would be your go-to dare?",
  "201. If you could choose between having sex 3 times a week for the rest of your life or don't have at all what would you pick?",
  "202. One mistake you made and regretted but if you had the chance to do it, you'd do it again?",
  "203. Who am I to you?",
  "204. Ever had a pregnancy scare?",
  "205. Craziest sexual thing you've done with the OPPOSITE gender? No lies please."
];

// Command implementation
smd(
  {
    cmdname: "questiongame",
    desc: "Sends a random question from a list of fun and spicy questions.",
    react: "🔥",
    type: "game",
    filename: __filename,
  },
  async (m) => {
    try {
      // Select a random question
      const randomQuestion = questions[Math.floor(Math.random() * questions.length)];
      
      // Send the question as a reply
      await m.reply(randomQuestion);
    } catch (e) {
      m.error(`${e}\n\nCommand: questiongame`, e, false);
    }
  }
);
